// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.16.0
// source: navigation.proto

package navigation

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_navigation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_navigation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_navigation_proto_rawDescGZIP(), []int{0}
}

type NavigationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groundspeed   string `protobuf:"bytes,1,opt,name=groundspeed,proto3" json:"groundspeed,omitempty"`
	Verticalspeed string `protobuf:"bytes,2,opt,name=verticalspeed,proto3" json:"verticalspeed,omitempty"`
	Longitude     string `protobuf:"bytes,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      string `protobuf:"bytes,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Altitude      string `protobuf:"bytes,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Altitudeagl   string `protobuf:"bytes,6,opt,name=altitudeagl,proto3" json:"altitudeagl,omitempty"`
	Pitch         string `protobuf:"bytes,7,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Roll          string `protobuf:"bytes,8,opt,name=roll,proto3" json:"roll,omitempty"`
	Heading       string `protobuf:"bytes,9,opt,name=heading,proto3" json:"heading,omitempty"`
}

func (x *NavigationMessage) Reset() {
	*x = NavigationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_navigation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NavigationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationMessage) ProtoMessage() {}

func (x *NavigationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_navigation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationMessage.ProtoReflect.Descriptor instead.
func (*NavigationMessage) Descriptor() ([]byte, []int) {
	return file_navigation_proto_rawDescGZIP(), []int{1}
}

func (x *NavigationMessage) GetGroundspeed() string {
	if x != nil {
		return x.Groundspeed
	}
	return ""
}

func (x *NavigationMessage) GetVerticalspeed() string {
	if x != nil {
		return x.Verticalspeed
	}
	return ""
}

func (x *NavigationMessage) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *NavigationMessage) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *NavigationMessage) GetAltitude() string {
	if x != nil {
		return x.Altitude
	}
	return ""
}

func (x *NavigationMessage) GetAltitudeagl() string {
	if x != nil {
		return x.Altitudeagl
	}
	return ""
}

func (x *NavigationMessage) GetPitch() string {
	if x != nil {
		return x.Pitch
	}
	return ""
}

func (x *NavigationMessage) GetRoll() string {
	if x != nil {
		return x.Roll
	}
	return ""
}

func (x *NavigationMessage) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

var File_navigation_proto protoreflect.FileDescriptor

var file_navigation_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0e,
	0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x97,
	0x02, 0x0a, 0x11, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x61, 0x67,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x61, 0x67, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x32, 0x5a, 0x0a, 0x0a, 0x4e, 0x61, 0x76, 0x69,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x1d, 0x2e, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e,
	0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x69, 0x62, 0x75, 0x6d, 0x69, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x65, 0x73, 0x2d, 0x61, 0x76, 0x69, 0x6f, 0x6e, 0x69, 0x63, 0x73, 0x2d, 0x70,
	0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_navigation_proto_rawDescOnce sync.Once
	file_navigation_proto_rawDescData = file_navigation_proto_rawDesc
)

func file_navigation_proto_rawDescGZIP() []byte {
	file_navigation_proto_rawDescOnce.Do(func() {
		file_navigation_proto_rawDescData = protoimpl.X.CompressGZIP(file_navigation_proto_rawDescData)
	})
	return file_navigation_proto_rawDescData
}

var file_navigation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_navigation_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),      // 0: navigation.EmptyMessage
	(*NavigationMessage)(nil), // 1: navigation.NavigationMessage
}
var file_navigation_proto_depIdxs = []int32{
	0, // 0: navigation.Navigation.GetNavigation:input_type -> navigation.EmptyMessage
	1, // 1: navigation.Navigation.GetNavigation:output_type -> navigation.NavigationMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_navigation_proto_init() }
func file_navigation_proto_init() {
	if File_navigation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_navigation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_navigation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NavigationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_navigation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_navigation_proto_goTypes,
		DependencyIndexes: file_navigation_proto_depIdxs,
		MessageInfos:      file_navigation_proto_msgTypes,
	}.Build()
	File_navigation_proto = out.File
	file_navigation_proto_rawDesc = nil
	file_navigation_proto_goTypes = nil
	file_navigation_proto_depIdxs = nil
}
